#!/bin/bash
clear
# "This script is created by Raghu kumar Gone"
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
NORMAL="\033[0;39m"
clear
target="None"
my_head()
{
  echo -e $BIBlue"========================================================================================================"$NORMAL
  echo -e $BIYellow"\tAutomation Tool to automate day to day  unix Tasks !! \c"
  echo -e "\tTarget Server : $target"$NORMAL
  echo -e $BIBlue"========================================================================================================"$NORMAL

}

while true
do
my_head
    echo -e $BIRed"Please select you choice from below menu \n"
    echo -e " 1. Pre-Validation \n"
    echo -e " 2. User Adminstration \n"
    echo -e " 3. Run Adhoc Commands \n"
    echo -e "22. Choose the Target Server \n"
    echo -e " 0. Exit \n"$NORMAL

    read choice
    case $choice in
    0)
    break
    ;;
    1)
    echo "Welcome to Pre-Validation"
    sleep 4
    ;;
    2)
        while true
          do

              echo -e $BIPurple"1. user creation \n"
              echo -e "2. user removal \n"
              echo -e "3. Group Add \n"
              echo -e "0. Exit \n"$NORMAL
              read choice_user_admin
              case $choice_user_admin in
                0)
                  break
                ;;
                1)
                  echo -e "Welcome to user Creation \n"
                  sleep 2
                  ;;
                2)
                  echo -e  "Welcome to user removal \n"
                  sleep 2
                  ;;
                3)
                  echo -e "Welcome to Group Add \n"
                  sleep 2
                  ;;
                *)
                 echo -e "wrong choice !!! \n"
                 read dummy
                 continue
                 ;;
               esac
             done
             ;;
    3)
    echo "Welcome to Run Adhoc Commands"
    sleep 4
    ;;
    22)
          while true
            do
              clear
              my_head
              echo -e "1. Target Server \n"
              echo -e "0. Exit \n"
              echo -e " Enter you choice \c"
              read choose_target_in_hosts_file
            case $choose_target_in_hosts_file in
              0)
                clear
                break
                ;;
             1)
                echo -e "=========================================================================="
                echo -e "Available Environments  : All --> for all servers in this Env or Host IP"
                cat /etc/ansible/hosts| grep "\["| sed "s/\[/ /g" | sed "s/\]/ /g"
                echo -e "=========================================================================="
                echo -e "Enter your choice : \c"
                read target
                ;;
              esac
          done
          ;;
    *)
    echo "Wrong choice !!!!  \n"
    read dummy
    continue
    ;;
    esac
done
