---
- hosts: webservice
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: latest
    - name: start the service and enabled
      service:
        name: httpd
        state: started
        enabled: true
