---
- hosts: test
  become: true
  become_user: root
  tasks:
    - name: Ansible loops with when condition
      debug:
        msg: "{{item}}"
      with_items:
        - "hello1"
        - "hello2"
      when: ansible_os_family == "RedHat"
